/* tslint:disable */
/* eslint-disable */
/**
 * Team Connect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInDto
 */
export interface LogInDto {
    /**
     * 
     * @type {string}
     * @memberof LogInDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LogInDto
     */
    password: string;
}

/**
 * Check if a given object implements the LogInDto interface.
 */
export function instanceOfLogInDto(value: object): value is LogInDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LogInDtoFromJSON(json: any): LogInDto {
    return LogInDtoFromJSONTyped(json, false);
}

export function LogInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LogInDtoToJSON(json: any): LogInDto {
    return LogInDtoToJSONTyped(json, false);
}

export function LogInDtoToJSONTyped(value?: LogInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

