/* tslint:disable */
/* eslint-disable */
/**
 * Team Connect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpDto
 */
export interface SignUpDto {
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpDto
     */
    password: string;
}

/**
 * Check if a given object implements the SignUpDto interface.
 */
export function instanceOfSignUpDto(value: object): value is SignUpDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignUpDtoFromJSON(json: any): SignUpDto {
    return SignUpDtoFromJSONTyped(json, false);
}

export function SignUpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignUpDtoToJSON(json: any): SignUpDto {
    return SignUpDtoToJSONTyped(json, false);
}

export function SignUpDtoToJSONTyped(value?: SignUpDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

