/* tslint:disable */
/* eslint-disable */
/**
 * Team Connect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokensEntity
 */
export interface TokensEntity {
    /**
     * 
     * @type {string}
     * @memberof TokensEntity
     */
    accessToken: string;
}

/**
 * Check if a given object implements the TokensEntity interface.
 */
export function instanceOfTokensEntity(value: object): value is TokensEntity {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function TokensEntityFromJSON(json: any): TokensEntity {
    return TokensEntityFromJSONTyped(json, false);
}

export function TokensEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokensEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
    };
}

export function TokensEntityToJSON(json: any): TokensEntity {
    return TokensEntityToJSONTyped(json, false);
}

export function TokensEntityToJSONTyped(value?: TokensEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
    };
}

